trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendProject: 'Inventory.Api/Inventory.Api.csproj'
  frontendPath: 'inventory.web'
  azureSubscription: 'IMS-Azure-Connection'
  webAppName: 'ims-api-stephan'

steps:

# Install .NET 8
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Build Backend
- script: dotnet restore $(backendProject)
  displayName: Restore Backend

- script: dotnet build Inventory.Api/Inventory.Api.csproj --configuration Release --no-restore
  displayName: Build Backend

- script: dotnet publish Inventory.Api/Inventory.Api.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)/backend
  displayName: Publish Backend

# Install Node.js
- task: UseNode@1
  inputs:
    version: '20.19.0'

- script: |
    node -v
    npm -v
    npm cache clean --force
    npm ci --include=optional --foreground-scripts
  workingDirectory: $(frontendPath)
  displayName: Install Frontend Packages

- script: npm run build
  workingDirectory: $(frontendPath)
  displayName: Build Frontend

- task: AzureWebApp@1
  displayName: Deploy Backend to Azure App Service
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/backend'