trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendProject: 'Inventory.Api/Inventory.Api.csproj'
  frontendPath: 'inventory.web'

steps:

# Install .NET 8
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Build Backend
- script: dotnet restore $(backendProject)
  displayName: Restore Backend

- script: dotnet build $(backendProject) --configuration Release --no-restore
  displayName: Build Backend

# Install Node.js
- task: UseNode@1
  inputs:
    version: '20.19.0'

- script: |
    node -v
    npm -v
    npm cache clean --force
    npm ci --include=optional --foreground-scripts
  workingDirectory: $(frontendPath)
  displayName: Install Frontend Packages

- script: npm run build
  workingDirectory: $(frontendPath)
  displayName: Build Frontend